### ISSUE TITLE
Go version uses unnecessarily slow sort

### ISSUE THREAD

**Issue by twpayne** [Ecostack/wasm-rust-go-asc#2]
The Go versions [uses `sort.Stable`](https://github.com/Ecostack/wasm-rust-go-asc/blob/8f6f4d700db3a37bc0be078b0241cfada8ac8643/go/main.go#L28) which [uses an interface](https://github.com/Ecostack/wasm-rust-go-asc/blob/8f6f4d700db3a37bc0be078b0241cfada8ac8643/go/main.go#L13-L17).

Performance can significantly be improved by using [using `sort.Ints`](https://pkg.go.dev/sort#Ints) instead.

**Comment by Ecostack** [comment]
It is indeed true that the `sort.Stable` is slower than `sort.Ints`.
To be fair though, Rust and AssemblyScript both use stable sorts by default and `sort.Ints` is an unstable one.

Initially I started with `sort.Ints` and changed to the stable sort afterwards.

**Comment by twpayne** [comment]
It does not make sense to use a stable sort when sorting ints as ints are fungible, i.e. if the you sort the array 1, 2, 2, 3 and the sort swaps the positions of the 2s, it does not matter as you cannot tell the difference between the two 2s anyway, i.e. the result is identical whether the sort is stable or not.

The correct fix is then to update the Rust and AssemblyScript versions to use unstable sorts as well, or change the benchmark such that a stable sort is required, which would require changing the elements being sorted to be non-fungible.

**Comment by twpayne** [comment]
Let me know if you'd like a PR to fix the Go code, otherwise I'll assume that you don't want to fix this and I'll close this issue.

**Comment by Ecostack** [comment]
If you were to change all sorts into an unstable one, you could go ahead with a PR.
Actually, I would like to conduct a test which uses the same sort algorithm, be it stable or unstable.

At the moment, all code uses stable ones but the algorithms used are still inconsistent.

**Comment by twpayne** [comment]
> If you were to change all sorts into an unstable one, you could go ahead with a PR.

This makes no sense. The problem being solved here does not require a stable sort, and the difference in speed between stable and unstable sorts is extremely small. I also don't know Rust or AssemblyScript and so could not represent these languages fairly.

So, I'll close this issue and this can remain as yet another badly-designed benchmark on the internet.

https://xkcd.com/386/
